<?php

namespace ISETSO\MagazineBundle\Repository\Local;

/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param TypeLocal $typeLocal
     * @return Query
     */
    public function findAllBy($typeLocal)
    {
        return $this->createQueryBuilder('f')
                    ->join('f.user', 'u')
                    ->join('f.typeLocal', 'm')
                    ->where('m.id = :id')
                    ->setParameter('id',$typeLocal->getId());
    }

    /**
     * @param TypeLocal $typeLocal
     * @param \ISETSO\UserBundle\Entity\User\User $user
     * @return Query
     */
    public function findByUserAndBy($typeLocal,$user)
    {
        return $this->createQueryBuilder('f')
                        ->join('f.user', 'u')
                        ->join('f.typeLocals', 'm')
                        ->where('u.id = :id')
                        ->setParameter('id',$user->getId())
                        ->andWhere('m.id = :id')
                        ->setParameter('id',$typeLocal->getId());
    }

	/**
     * @return Query
     */
    public function findAll()
    {
        return $this->createQueryBuilder('f')
                    ->join('f.user', 'u');
    }

    /**
     * @param \ISETSO\UserBundle\Entity\User\User $user
     * @return Query
     */
    public function findByUser($user)
    {
        return $this->createQueryBuilder('f')
                        ->join('f.user', 'u')
                        ->where('u.id = :id')
                        ->setParameter('id',$user->getId());
    }

    /**
     * @param String $field
     * @param \ISETSO\UserBundle\Entity\User\User $user
     * @return Query
     */
    public function findByAnything($query , $field)
    {
        return  $query->andWhere('f.id like :search OR f.designation LIKE :search OR s.designation LIKE :search OR u.username LIKE :search')
                    ->setParameter('search', '%'.$field.'%')
                    ->orderBy('f.id', 'ASC');
    }
}
