<?php

namespace ISETSO\MagazineBundle\Repository\DetailArticleManagement;

/**
 * DetailOrderArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailOrderArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEntityBy($isManager , $isSimpleUser , $user)
    {
    	$query = null;
    	
    	if ($isManager && $user->isUser($user)){
    		$query = $this->createQueryBuilder('a')
    						->join('a.user', 'u');
    		
    	}else
    	if (!$isManager && $isSimpleUser && $user->isUser($user)){
    		$query = $this->createQueryBuilder('a')
    						->join('a.user', 'u')
                            ->where('u.id = :id')
                            ->setParameter('id',$user->getId());
    		
    	}
        return $query;
    }

    public function searchForm($query , $searchField)
    {
    	return  $query->andWhere('f.id like :search OR f.designation LIKE :search OR u.username LIKE :search')
                    			->setParameter('search', '%'.$searchField.'%')
                    			->orderBy('f.id', 'ASC');
    }
}
