<?php

namespace ISETSO\UserBundle\Repository\Message;
use Doctrine\ORM\Query;
/**
 * UserHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserMessage(\ISETSO\UserBundle\Entity\User\User $user = null)
	{
        return $this->createQueryBuilder('t')
                ->select("t.id, m.body ,s.username , mm.isRead")

                ->join('t.metadata', 'tm')               
                ->join('t.messages', 'm')
                ->join('m.metadata', 'mm')
                ->join('mm.participant', 'p')
                ->join('m.sender' , 's')

                

                ->andWhere('p.id = :participant')
                ->setParameter('participant', $user->getId())

                ->andWhere('t.isSpam = :isSpam')
                ->setParameter('isSpam', false, \PDO::PARAM_BOOL)

                ->andWhere('tm.isDeleted = :isDeleted')
                ->setParameter('isDeleted', false, \PDO::PARAM_BOOL)

                ->andWhere('tm.lastParticipantMessageDate IS NOT NULL')
                
                ->orderBy('tm.lastParticipantMessageDate', 'DESC')
                
                ->groupBy('t.id')
                ->getQuery()
                ->getResult()
                ;


	}
}
