<?php

namespace ISETSO\MagazineBundle\Repository\Magazine;

/**
 * DetailMagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailMagazineRepository extends \Doctrine\ORM\EntityRepository
{
}
