<?php

namespace ISETSO\MagazineBundle\Repository\Article;

use Doctrine\ORM\Query\Expr;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{   
}
